---
extends: default

rules:
  line-length:
    level: warning
  new-line-at-end-of-file:
    level: warning
  trailing-spaces:
    level: warning
ignore: |
  /doc/
  /web/node_modules
  /web/modules
  
