name: test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - devel
      - main
  pull_request:
    branches:
      - master
      - devel
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 
      - uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
      
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          npm install --force
          npm audit fix
          npm run build --if-present
          npm run test
          npm run testbuild
        working-directory: web
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          working-dir: "web"
          deploy-branch: gh-pages
          skip-publish: true
